name: deploy

on:
  push:
    branches:
    - master
    - development

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build project
      run: |
        npm ci
        npm run build

    - name: Set to live if branch is master
      if: github.ref == 'refs/heads/master'
      run: |
        sudo apt-get install jq
        jq -c '.site = $newVal' --arg newVal charge-hub' <<<"$jsonStr" firebase.json > tmp.$$.json && mv tmp.$$.json firebase.json

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}