name: deploy

on:
    push:
        branches:
            - main
            - development

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build project
              run: |
                  cd web-app
                  npm ci
                  npm run build

            - name: Set to live if branch is main
              if: github.ref == 'refs/heads/main'
              run: |
                  contents="$(jq '.hosting.site = "charge-hub"' firebase.json)" && \
                  echo "${contents}" > firebase.json

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
