name: deploy

on:
    push:
        branches:
            - main
            - development

env:
    WEBAPP_PATH: 'web-app/'
    FUNCTIONS_PATH: 'cloud-functions/'

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Node.js dependencies
              run: |
                  cd ${{ env.WEBAPP_PATH }}; npm ci; cd ..;
                  cd ${{ env.FUNCTIONS_PATH }}; npm ci; cd ..;

            - name: Build Web App
              run: |
                  cd ${{ env.WEBAPP_PATH }}
                  npm run build

            - name: Set to live if branch is main
              if: github.ref == 'refs/heads/main'
              run: |
                  contents="$(jq '.hosting.site = "charge-hub"' firebase.json)" && \
                  echo "${contents}" > firebase.json

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
