name: lint

on: push

env:
    - WEBAPP_PATH: 'web-app/'

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Node.js dependencies
              run: |
                  cd ${{ env.WEBAPP_PATH }}; npm ci; cd ..;
                  cd ${{ env.FUNCTIONS_PATH }}; npm ci; cd ..;

            - name: Run linters on Web App
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  auto_fix: true

                  # Enable linters
                  eslint: true
                  eslint_dir: ${{ env.WEBAPP_PATH }}/

                  prettier: true
                  prettier_dir: ${{ env.WEBAPP_PATH }}/

            - name: Run linters on Functions
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  auto_fix: true

                  # Enable linters
                  eslint: true
                  eslint_dir: ${{ env.FUNCTIONS_PATH }}

                  prettier: true
                  prettier_dir: ${{ env.FUNCTIONS_PATH }}
