name: lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]
3
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Node.js dependencies
              run: |
                  cd web-app; npm ci; cd ..;
                  cd functions; npm ci; cd ..;

            - name: Run linters on Web App
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  auto_fix: true

                  # Enable linters
                  eslint: true
                  eslint_dir: web-app/

                  prettier: true
                  prettier_dir: web-app/

            - name: Run linters on Functions
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  auto_fix: true

                  # Enable linters
                  eslint: true
                  eslint_dir: functions/

                  prettier: true
                  prettier_dir: functions/
